export const cities = [
  "Ajax",
  "Barrie",
  "Belleville",
  "Brampton",
  "Brantford",
  "Brockville",
  "Burlington",
  "Cambridge",
  "Chatham-Kent",
  "Cornwall",
  "Dryden",
  "Elliot Lake",
  "Greater Sudbury",
  "Guelph",
  "Haldimand",
  "Hamilton",
  "Kawartha Lakes",
  "Kenora",
  "Kingston",
  "Kirkland Lake",
  "Kitchener",
  "Lakeshore",
  "London",
  "Markham",
  "Midland",
  "Mississauga",
  "Moose Factory",
  "Moosonee",
  "Niagara Falls",
  "Niagara-on-the-Lake",
  "North Bay",
  "Orillia",
  "Oshawa",
  "Ottawa",
  "Parry Sound",
  "Pembroke",
  "Perth",
  "Peterborough",
  "Pickering",
  "Port Colborne",
  "Port Hope",
  "Sarnia",
  "Sault Ste. Marie",
  "St. Catharines",
  "St. Thomas",
  "Stratford",
  "Sudbury",
  "Temiskaming Shores",
  "Thorold",
  "Thunder Bay",
  "Timmins",
  "Toronto",
  "Windsor",
  "Woodstock",
];
